# Dependabot configuration for python-cookiecutter-typer-cli
# This keeps the cookiecutter template repository dependencies up to date

version: 2
updates:
  # Update GitHub Actions if any are added in the future
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "ltpitt"
    commit-message:
      prefix: "ci"
      include: "scope"